extends Node

var ERROR_TEXT_COLOR_HEX = "fb1a2f"
var STD_TEXT_COLOR_HEX = "ffffff"

enum TARGET_ACQUISITION_MODE { MAX_PROGRESS, FIRST_IN_RANGE }

enum FIRE_ANIMATION { NONE, INSTANT, PROJECTILE, MISSILE, BOMB, TRAP }
