extends Node

var player_init_health = 100

var player_init_money = 100

var tower_data = {
	"machine_gun_t_1": {
		"damage": 10,
		"rate_of_fire": 1,
		"range": 300,
		"animation_category": "projectile",
		"cost": 20,
		"shoot_sound": "",
	},
	"machine_gun_t_2": {
		"damage": 10,
		"rate_of_fire": 0.5,
		"range": 400,
		"animation_category": "projectile",
		"cost": 200,
		"shoot_sound": "",
	},
	"missile_t_1": {
		"damage": 100,
		"rate_of_fire": 3,
		"range": 500,
		"animation_category": "missile",
		"cost": 500,
		"shoot_sound": "",
		"reload_time": 1,
	},
	"cannon_t_1": {
		"damage": 200,
		"rate_of_fire": 5,
		"range": 750,
		"animation_category": "projectile",
		"cost": 1000,
		"shoot_sound": "",
	},
}

var mob_data = {
	"green_soldier": {
		"damage": 2,
		"reward": 3,
		"speed": 120,
		"hp": 30,
	},
	"brown_soldier": {
		"damage": 2,
		"reward": 7,
		"speed": 170,
		"hp": 40,
	},
	"blue_tank": {
		"damage": 5,
		"reward": 10,
		"speed": 80,
		"hp": 100,
	},
	"red_tank": {
		"damage": 5,
		"reward": 20,
		"speed": 140,
		"hp": 200,
	},
}

var wave_data = {
	"map_desert_a": [
		[
			{"mob_type": "blue_tank", "path": 1, "timeout": 3},
		],
		[
			{"mob_type": "blue_tank", "path": 1, "timeout": 3},
			{"mob_type": "blue_tank", "path": 1, "timeout": 3},
		],
	],
	"map_1": [
		[
			{"mob_type": "blue_tank", "path": 1, "timeout": 3},
		],
		[
			{"mob_type": "blue_tank", "path": 1, "timeout": 3},
			{"mob_type": "blue_tank", "path": 2, "timeout": 3},
		],
		[
			{"mob_type": "blue_tank", "path": 2, "timeout": 2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
		],
		[
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "blue_tank", "path": 2, "timeout": 2},
			{"mob_type": "blue_tank", "path": 2, "timeout": 2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
		],
		[
			{"mob_type": "red_tank", "path": 1, "timeout": 0.8},
		],
		[
			{"mob_type": "blue_tank", "path": 2, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 2, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 2, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 2, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 2, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 2, "timeout": 1.5},
		],
		[
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
			{"mob_type": "blue_tank", "path": 1, "timeout": 1.5},
		],
		[
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 2, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 2, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 2, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 2, "timeout": 0.8},
			{"mob_type": "blue_tank", "path": 2, "timeout": 0.8},
		],
		[
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
		],
		[
			{"mob_type": "red_tank", "path": 1, "timeout": 4},
			{"mob_type": "red_tank", "path": 1, "timeout": 4},
			{"mob_type": "red_tank", "path": 1, "timeout": 4},
		],
		[
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "red_tank", "path": 1, "timeout": 2},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.6},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.6},
		],
		[
			{"mob_type": "red_tank", "path": 1, "timeout": 0.7},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.7},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.7},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
			{"mob_type": "red_tank", "path": 1, "timeout": 0.7},
			{"mob_type": "blue_tank", "path": 1, "timeout": 2},
		],
		[
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.2},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
			{"mob_type": "blue_tank", "path": 1, "timeout": 0.1},
		],
	],
}

