extends Node

var player_init_health = 100

var player_init_money = 100

var tower_data = {
	"machine_gun_t_1": {
		"damage": 10,
		"rate_of_fire": 1,
		"range": 300,
		"animation_category": "projectile",
		"cost": 20,
	},
	"machine_gun_t_2": {
		"damage": 10,
		"rate_of_fire": 0.5,
		"range": 400,
		"animation_category": "projectile",
		"cost": 200,
	},
	"missile_t_1": {
		"damage": 100,
		"rate_of_fire": 3,
		"range": 500,
		"animation_category": "missile",
		"cost": 500,
		"reload_time": 1,
	},
	"cannon_t_1": {
		"damage": 200,
		"rate_of_fire": 5,
		"range": 750,
		"animation_category": "projectile",
		"cost": 1000,
	},
}

var mob_data = {
	"green_soldier": {
		"damage": 2,
		"reward": 3,
		"speed": 120,
		"hp": 30,
	},
	"brown_soldier": {
		"damage": 2,
		"reward": 7,
		"speed": 170,
		"hp": 40,
	},
	"blue_tank": {
		"damage": 5,
		"reward": 10,
		"speed": 80,
		"hp": 100,
	},
	"red_tank": {
		"damage": 5,
		"reward": 20,
		"speed": 140,
		"hp": 200,
	},
}

var wave_data = {
	"Map1": [
		[
			["blue_tank", 3],
		],
		[
			["blue_tank", 3],
			["blue_tank", 3],
		],
		[
			["blue_tank", 2],
			["blue_tank", 2],
			["blue_tank", 2],
			["blue_tank", 2],
		],
		[
			["blue_tank", 2],
			["blue_tank", 2],
			["blue_tank", 2],
			["blue_tank", 2],
			["blue_tank", 2],
			["blue_tank", 2],
			["blue_tank", 2],
			["blue_tank", 2],
		],
		[
			["red_tank", 0.8],
		],
		[
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
		],
		[
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
			["blue_tank", 1.5],
		],
		[
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
			["blue_tank", 0.8],
		],
		[
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
		],
		[
			["red_tank", 4],
			["red_tank", 4],
			["red_tank", 4],
		],
		[
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 2],
			["red_tank", 2],
			["red_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
			["blue_tank", 0.6],
		],
		[
			["red_tank", 0.7],
			["blue_tank", 2],
			["red_tank", 0.7],
			["blue_tank", 2],
			["red_tank", 0.7],
			["blue_tank", 2],
			["red_tank", 0.7],
			["blue_tank", 2],
		],
		[
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.2],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
			["blue_tank", 0.1],
		],
	],
}

